# Generated by Django 4.2.9 on 2025-08-13 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_type', models.CharField(choices=[('call', 'Call'), ('chat', 'Chat')], max_length=10)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('agent_id', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('tokens_input', models.IntegerField(blank=True, null=True)),
                ('tokens_output', models.IntegerField(blank=True, null=True)),
                ('tokens_total', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-created_at'),
                'indexes': [models.Index(fields=['external_id'], name='comms_commu_externa_f46dff_idx'), models.Index(fields=['comm_type', 'started_at'], name='comms_commu_comm_ty_b2c00c_idx')],
            },
        ),
    ]
