# Generated by Django 4.2.9 on 2025-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_retell_webhook_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communication',
            new_name='comms_commu_convers_e919b9_idx',
            old_name='comms_commu_conversa_idx',
        ),
        migrations.RenameIndex(
            model_name='communication',
            new_name='comms_commu_agent_i_ec0be0_idx',
            old_name='comms_commu_agent_id_idx',
        ),
        migrations.AlterField(
            model_name='communication',
            name='comm_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('chat', 'Chat')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='commsmessage',
            index=models.Index(fields=['message_id'], name='comms_comms_message_c99511_idx'),
        ),
    ]
