# Generated by Django 4.2.9 on 2025-08-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='brokers.broker'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
