# Generated by Django 4.2.9 on 2025-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CTASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="FontAwesome/Lucide CSS class", max_length=100
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="public/")),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("video_url", models.URLField(blank=True)),
                ("overlay", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("text", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("video_url", models.URLField(blank=True)),
                (
                    "align",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        default="left",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("price_month", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ("price_annual", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("cta_text", models.CharField(blank=True, default="Comenzar", max_length=100)),
                ("cta_url", models.URLField(blank=True, default="/auth/signup/")),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SEOPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=255)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("noindex", models.BooleanField(default=False)),
                ("canonical_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("brand_name", models.CharField(default="Trauck", max_length=150)),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="The Smart Dispatcher for Carriers", max_length=200
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True, default="Prepárate para tu CDL con Trauck", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True, default="Simulacros, analítica y asistencia por IA"
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(
                        blank=True, default="Comienza tu preparación CDL", max_length=100
                    ),
                ),
                ("primary_cta_url", models.URLField(blank=True, default="/auth/signup/")),
                (
                    "secondary_cta_text",
                    models.CharField(blank=True, default="Saber más", max_length=100),
                ),
                ("secondary_cta_url", models.URLField(blank=True, default="#features")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("logo_dark", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("favicon", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("footer_html", models.TextField(blank=True, default="© Trauck")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="support@trauck.com", max_length=254),
                ),
                ("contact_phone", models.CharField(blank=True, default="", max_length=50)),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=255)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="public/")),
                (
                    "twitter_card",
                    models.CharField(blank=True, default="summary_large_image", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="public/")),
                ("quote", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("company", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "abstract": False,
            },
        ),
    ]
