# Generated by Django 4.2.9 on 2025-08-10 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_profile', '0002_profile_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationalExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retell_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('agent_id', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('voice', 'voice'), ('web', 'web'), ('phone', 'phone'), ('whatsapp', 'whatsapp')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('exam_type', models.CharField(max_length=255)),
                ('score_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score_scale', models.CharField(choices=[('percentage', 'percentage'), ('points', 'points')], max_length=20)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('section_breakdown', models.JSONField(default=list)),
                ('transcript_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('communication_thread_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_sessions', to='my_profile.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSessionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='education.conversationalexamsession')),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'value'], name='education_e_key_34c273_idx')],
            },
        ),
    ]
