# Generated by Django 4.2.9 on 2025-08-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('items', models.JSONField(default=list, help_text='[{question_id, type, selected, correct, correct_answer}]')),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='IN_PROGRESS', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_questions', models.PositiveIntegerField(default=20)),
                ('difficulty_mix', models.JSONField(blank=True, help_text='e.g. {"easy":40, "medium":40, "hard":20}', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_templates', to='education.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSessionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('conversation_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='education.examattempt')),
            ],
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='education.examtemplate'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TF', 'True/False'), ('SC', 'Single Choice')], max_length=2)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/questions/')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'type', 'difficulty', 'is_active'], name='education_q_topic_i_0895a6_idx'), models.Index(fields=['-created_at'], name='education_q_created_31f1c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['is_active'], name='education_e_is_acti_31e322_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessionlink',
            index=models.Index(fields=['provider', 'conversation_id'], name='education_e_provide_d00f66_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'status'], name='education_e_user_id_095222_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['-started_at'], name='education_e_started_464374_idx'),
        ),
    ]
